# Generated by Django 3.2.6 on 2021-08-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('owner', models.UUIDField()),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='dogger.dogsize')),
            ],
        ),
    ]
