# Generated by Django 3.2.6 on 2021-08-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='dogger.dogsize'),
        ),
    ]
