# Generated by Django 3.2.6 on 2021-08-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogger', '0003_walkerscheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[('0', 'open'), ('1', 'complete'), ('2', 'canceled')])),
                ('owner', models.UUIDField()),
                ('walker', models.UUIDField()),
                ('date', models.DateField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='dogger.dog')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='dogger.walkerscheduler')),
            ],
        ),
    ]
