# Generated by Django 3.2.6 on 2021-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogger', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[('0', 'open'), ('1', 'complete'), ('2', 'canceled')], default='0'),
        ),
    ]
